import ClientOnly from "./components/ClientOnly";
import RegisterModal from "./components/RegisterModal";

import { Navabar } from "./components/navbar/Navabar";
import "./globals.css";
import { Nunito } from "next/font/google";

export const metadata = {
  title: "Airbnb",
  description: "Generated by create next app",
};
const font = Nunito({
  subsets: ["latin"],
});
export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={font.className}>
        <ClientOnly>
          <Navabar />
          <RegisterModal />
          {/* <Modal
            disabled={false}
            isOpen
            title={"Login"}
            actionLabel="Submit"
            secondaryActionLabel="Cancel"
            // onClose={() => console.log("onClose")}
            // onSubmit={() => console.log("onSubmit")}
          /> */}
        </ClientOnly>

        {children}
      </body>
    </html>
  );
}
